apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |-
    server {
      listen 80 default_server;
      server_name _;
      default_type text/plain;
      location / {
        return 200 'Hello! I am $hostname!\nOK\n';
      }
      location /tasty {
        proxy_pass http://nginx-service:8080;
      }
    }



